version: '3.8'
services:
  api:
    container_name: product-api
    image: products-api:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 80:80
    depends_on:
      mssql:
        condition: service_healthy
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "1q2w3e4r+!"
    ports:
      - 1433:1433
    volumes:
      - mssql-data:/var/opt/mssql
volumes:
  mssql-data:
